---
title: "STAT 626 Time Series - Group 1 Project - Forecasting the Flu"
author: "Group 1 / Alex Hughes"
format: gfm
---

## Libraries and plot theme

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(astsa)
library(lubridate)
theme_set(theme_bw())
```

## Flu data

```{r message=FALSE, warning=FALSE}
flu <- read_csv("VIW_FNT.csv")
head(flu)
```

## Aggregate across countries to create flu count by date time series datasets for Influenza A, B, and all strains

```{r 'aggregate datasets'}
InfA <- flu %>% 
  group_by(ISO_WEEKSTARTDATE) %>%
  summarise(total_flu = sum(INF_A, na.rm = T))

InfB <- flu %>%
  group_by(ISO_WEEKSTARTDATE) %>%
  summarise(total_flu = sum(INF_B, na.rm = T))

InfA$subtype <- "Inf_A"
InfB$subtype <- "Inf_B"

flu_df <- bind_rows(InfA, InfB)

InfAll <- flu %>% # contains more than just A and B; many strains
  group_by(ISO_WEEKSTARTDATE) %>%
  summarise(total_flu = sum(INF_ALL, na.rm = T))
```

## Plot Influenza A over time

```{r 'infA over time'}
# ggplot(flu, aes(x = ISO_WEEKSTARTDATE, y = INF_A))+
#   geom_line()

ggplot(InfA, aes(x = ISO_WEEKSTARTDATE, y = total_flu))+
  geom_line()+
  labs(x = "Time (in weeks)", y = "Influenza A number of specimens")

ggsave('InfA-by-year.png')
```

## Plot Influenza A vs Influenza B over time

```{r 'infA and infB over time'}
ggplot(flu_df, aes(x = ISO_WEEKSTARTDATE, y = total_flu, color = subtype))+
  geom_line()+
  labs(x = "Time (in weeks)", y = "Number of specimens")

ggsave('InfA-vs-InfB-time-series.png')
```

```{r}
tsplot(flu$INF_A)
```

# Merge flu and drought

Drought data was downloaded from https://droughtmonitor.unl.edu/DmData/DataDownload/DSCI.aspx

```{r}
dr <- read_csv("dm_export_20010101_20101231.csv")

drought_clean <- dr %>%
  mutate(MapDate = ymd(MapDate)) %>%
  mutate(MMWR_WEEK = epiweek(MapDate), #create mmwr week and year variables for matching w/ flu dataset
         MMWR_YEAR = epiyear(MapDate))

USAflu <- flu %>%
  filter(COUNTRY_CODE == "USA") %>%
  filter(MMWR_WEEKSTARTDATE > as.Date("2000-12-31") & MMWR_WEEKSTARTDATE <= as.Date("2010-12-31")) %>%
  dplyr::select(MMWR_WEEK, MMWR_YEAR, INF_A, INF_B, INF_ALL)

df <- left_join(USAflu, drought_clean, by = c("MMWR_WEEK", "MMWR_YEAR")) %>%
  arrange(MapDate)

# want complete cases only

df <- df[complete.cases(df[ , c("MMWR_WEEK", "MMWR_YEAR", "INF_A", "INF_B", "INF_ALL", "DSCI")]), ] 

write_csv(df, 'complete-flu-drought-2001-2010.csv')
```

